const ACTION_TYPE_ADD_WORD = 'ADD_WORD';
const ACTION_TYPE_TOGGLE_WORD = 'TOGGLE_WORD';
const ACTION_TYPE_REMOVE_WORD = 'REMOVE_WORD';

export default {
  ACTION_TYPE_ADD_WORD,
  ACTION_TYPE_TOGGLE_WORD,
  ACTION_TYPE_REMOVE_WORD,
};
